//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceTracking.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthData
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public Nullable<int> IdSpecialist { get; set; }
    
        public virtual Specialist Specialist { get; set; }
    }
}
