//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceTracking.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoSpecialist
    {
        public int id { get; set; }
        public string fio { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Roles { get; set; }
        public string groups { get; set; }
    }
}
