//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceTracking.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleSpecialist
    {
        public int Id { get; set; }
        public int IdRole { get; set; }
        public int IdSpecialist { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
