//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceTracking.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentParents
    {
        public int Id { get; set; }
        public int IdParents { get; set; }
        public int IdStudent { get; set; }
        public int IdRelationship { get; set; }
    
        public virtual Parents Parents { get; set; }
        public virtual Relationship Relationship { get; set; }
        public virtual Student Student { get; set; }
    }
}
