//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceTracking.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentShedule
    {
        public int Id { get; set; }
        public int IdStudent { get; set; }
        public int IdShedule { get; set; }
        public string Score { get; set; }
    
        public virtual Shedule Shedule { get; set; }
        public virtual Student Student { get; set; }
    }
}
